#!/bin/bash

while :
do
    echo -n "Enter the program name to run (or 'q' to quit): "
    read program_name
    
    if [ "$program_name" = "q" ]; then
        break
    fi

    while :
    do
        leaks $program_name
        sleep 0.5
    done
done